# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# Work on master branch
trigger:
- master

# Uses microsoft virtual machine
# Will only use things in Git repo
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln' # crawl until find solution file
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release' # Release mode (as opposed to debug)

# Get NuGet ready
steps:
- task: NuGetToolInstaller@1

# Store NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build and compile
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run all unit tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
